### ISSUE TITLE
Implement "Run Again" option to re-run a job with tweaked parameters

### ISSUE THREAD

**Issue by drpowell** [MonashBioinformaticsPlatform/laxy#10]
Doesn't seem to re-submit.

**Comment by pansapiens** [comment]
Button is currently a placeholder - I've removed the buttons for the moment to avoid false expectations and edited this issue to reflect that it's a feature to be implemented, not a bug.

**Comment by pansapiens** [comment]
Related: #27

**Comment by pansapiens** [comment]
This feature now works, but the stepper/wizard UI doesn't jump to a sensible step upon cloning the job parameters. Opened a new issue for this: https://github.com/MonashBioinformaticsPlatform/laxy/issues/46
