### ISSUE TITLE
no option for GRCh38?

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#16]
seems to be two version of GRCh37, but no 38 on the pipeline selection screen?

**Comment by pansapiens** [comment]
The list of available genomes will certainly be expanded - currently anything in iGenomes (via https://github.com/ewels/AWS-iGenomes) can be added easily (and is downloaded automatically to the compute node on demand). The list is currently hard-coded in the frontend and backend - ideally we want a REST API endpoint that returns all the available genomes to the frontend. Some UI work also needs to be down to present the 'common' genomes alongside more obscure options without having a ludicrously long dropdown list.

I've added `NCBI/GRCh38` and `UCSC/hg38`, anyhow.
