### ISSUE TITLE
Count files on summary page, unclear to new user, which count file to use

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#26]
All the count files are presented in the summary page, it is unclear which to send to degust to first time users.

Parse only count files containing "withNames" as these are in the correct format, others are not.

**Comment by pansapiens** [comment]
Fixed. Only the 'withNames' files are now tagged as 'degust' so they get the 'send to degust' action button.

The next release of RNAsik should generate Degust compatible files for Forward/Reverse/NonStranded, so once that is release Laxy will provide all three options (https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/issues/42), and highlight the best option if available based on strand guessing.
