### ISSUE TITLE
View html files from laxy (qualimap, fastqc)

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#28]
Possible to have a view html option for html output from RNASik? (qualimap, fastqc). 

Taking qualimap discussion onboard there are some useful metrics that multiqc doesn't present. Spliced reads, and proportion of canonical reads.

Also, fastqc can be helpful too, seeing what the sequences are that are over-represented.

**Comment by pansapiens** [comment]
FastQC reports are now listed in the reports section - we may need a special paginated list for runs with many samples. Qualimap will be included (or excluded) once issues with qualimap results in RNAsik are resolved (https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/issues/43).

I'll close this for now and maybe open a new bug in the future to deal with long lists of reports (eg many samples).
