### ISSUE TITLE
Error if you do not select a reference genome

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#5]
Laxy run will error out, if you do not select a reference genome to align to (looks to default to hg19). Run name entry and selection of reference genome is sadly hidden when all the samples are listed out.

**Comment by pansapiens** [comment]
Thanks. Genome now must be selected before hitting the "Start job" button.

Fixed by commit https://github.com/MonashBioinformaticsPlatform/laxy/commit/64ad2e72e7e99227b804a0791e7e5c84afe0d784
