### ISSUE TITLE
selection of files from a URL, add files button does not trigger addition to shopping cart if all are selected

### ISSUE THREAD

**Issue by methylnick** [MonashBioinformaticsPlatform/laxy#51]
Samples are named like: `VTL153-D0-CD8_S10_L001_R1_001.fastq.gz`, `VTL153-D0-CD8_S10_L001_R2_001.fastq.gz`, `VTL153-D0-CD8_S10_L002_R1_001.fastq.gz` and `VTL153-D0-CD8_S10_L002_R2_001.fastq.gz`, etc

Laxy finds the files okay, selecting all and adding to cart does nothing (used chrome and firefox). 

Adding the first sample pair (`VTL153-D0-CD8_S10_L001_R1_001.fastq.gz`, `VTL153-D0-CD8_S10_L001_R2_001.fastq.gz`) worked, but no more.

**Comment by pansapiens** [comment]
Thanks - looks like this is an issue with merging technical replicates (same sample name across L001 and L002, eg `sampleA_S10_L001_R1_001.fastq.gz` and `sampleA_S10_L002_R1_001.fastq.gz`).

Traceback:

```
vue.esm.js?efeb:628 [Vue warn]: Error in v-on handler: "TypeError: str.split is not a function"

found in

---> <MdButton>
       <MdLayout>
         <RemoteFileSelect> at src/components/RemoteSelect/RemoteFilesSelect.vue
           <MdLayout>... (1 recursive calls)
             <InputFilesForm> at src/components/InputFilesForm.vue
               <MdStep>
                 <MdWhiteframe>
                   <MdStepper>
                     <RNASeqSetup> at src/components/RNASeqSetup.vue
                       <Root>
vue.esm.js?efeb:1896 TypeError: str.split is not a function
    at Object.reverseString (util.ts?d872:60)
    at VueComponent.RemoteFileSelect.addToCart (RemoteFilesSelect.vue?8d65:232)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at Proxy.invoker (vue.esm.js?efeb:2187)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at Proxy.Vue.$emit (vue.esm.js?efeb:3872)
    at Proxy.Vue.(:8002/anonymous function) (chrome-extension://nhdogjmejiglipccpnnnanhbledajbpd/build/backend.js:1056:28)
    at click (vue-material.js?2e0c:6)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at HTMLButtonElement.invoker (vue.esm.js?efeb:2187)
```

**Comment by methylnick** [comment]
tried merging the files and removing the _L00n suffix, however, the error still persists. That being said, it was possible to add samples individually (read pair) one at a time, selecting all, still doesn't work. 


`VTL153_D0_CD8_S10_R1_001.fastq.gz
VTL153_D0_CD8_S10_R2_001.fastq.gz
VTL153_D0_DP_S9_R1_001.fastq.gz
VTL153_D0_DP_S9_R2_001.fastq.gz
VTL153_D7_CD8_S12_R1_001.fastq.gz
VTL153_D7_CD8_S12_R2_001.fastq.gz
VTL153_D7_DP_S11_R1_001.fastq.gz
VTL153_D7_DP_S11_R2_001.fastq.gz
VTL24_D0_CD8_S2_R1_001.fastq.gz
VTL24_D0_CD8_S2_R2_001.fastq.gz
VTL24_D0_DP_S1_R1_001.fastq.gz
VTL24_D0_DP_S1_R2_001.fastq.gz
VTL24_D2_CD8_S4_R1_001.fastq.gz
VTL24_D2_CD8_S4_R2_001.fastq.gz
VTL24_D2_DP_S3_R1_001.fastq.gz
VTL24_D2_DP_S3_R2_001.fastq.gz
VTL24_D5_CD8_S6_R1_001.fastq.gz
VTL24_D5_CD8_S6_R2_001.fastq.gz
VTL24_D5_DP_S5_R1_001.fastq.gz
VTL24_D5_DP_S5_R2_001.fastq.gz
VTL24_D7_CD8_S8_R1_001.fastq.gz
VTL24_D7_CD8_S8_R2_001.fastq.gz
VTL24_D7_DP_S7_R1_001.fastq.gz
VTL24_D7_DP_S7_R2_001.fastq.gz`

**Comment by pansapiens** [comment]
Note to self:  add technical replicates / `_L001_`, `_L002_` examples to a standard testing dataset.
